name: TestPyPI
on:
  push:
    branches:
      - main
jobs:
  test_pypi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.0

    - name: Setup Python
      uses: actions/setup-python@v3.0.0
      with:
        python-version: '3.10'
        architecture: x64

    - name: Install Poetry
      run: pip install poetry==1.1.13

    - name: Set temp version
      run: >-
        poetry version patch &&
        version=$(poetry version | awk '{print $2}') &&
        poetry version $version.dev.$(date +%s)

    - name: Build project
      run: poetry build

    - name: pypi-publish
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
