name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    name: Python ${{ matrix.python-version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.0

    - name: Setup Python
      uses: actions/setup-python@v3.0.0
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install Poetry
      run: pip install poetry==1.1.13

    - name: Install nox and nox-Poetry
      run: |
        pip install nox==2022.1.7
        pip install nox-poetry==0.9.0
    
    - name: Run nox
      run: nox --python=${{ matrix.python-version }}

    - name: List files
      run: |
        pwd
        ls -la

    - name: Upload coverage data
      if: always()
      uses: "actions/upload-artifact@v3"
      with:
        name: coverage-data
        if-no-files-found: error
        path: |
          ".coverage"
          ".coverage.*"

  coverage: 
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.0

    - name: Setup Python
      uses: actions/setup-python@v3.0.0
      with:
        python-version: '3.10'
        architecture: x64

    - name: Install Poetry
      run: pip install poetry==1.1.13

    - name: Install nox and nox-poetry
      run: |
        pip install nox==2022.1.7
        pip install nox-poetry==0.9.0

    - name: Download coverage data
      uses: actions/download-artifact@v3
      with:
        name: coverage-data

    - name: Combine coverage data and display human readable report
      run: nox --session=coverage

    - name: Create xml coverage report
      run: nox --session=coverage -- xml

    - name: Codecov
      uses: codecov/codecov-action@v2.1.0

